spring:
  application:
    name: movie-service
  main:
    allow-bean-definition-overriding: true
server:
  port: 9091

resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 10000
        slidingWindowType: COUNT_BASED
    instances:
      comment-service:
        baseConfig: default
        waitDurationInOpenState: 15000
      reservation-service:
        baseConfig: default
        waitDurationInOpenState: 20000
      log-service:
        baseConfig: default
        waitDurationInOpenState: 20000
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200
    instances:
      comment-service:
        baseConfig: default
